<?php

function xgettext_dummy()
{
__(  "loc" );
__(  "01" );
__(  "02" );
__(  "03" );
__(  "04" );
__(  "05" );
__(  "06" );
__(  "07" );
__(  "08" );
__(  "11" );
__(  "12" );
__(  "13" );
__(  "14" );
__(  "15" );
__(  "16" );
__(  "17" );
__(  "18" );
__(  "19" );
__(  "20" );
__(  "21" );
__(  "22" );
__(  "23" );
__(  "24" );
__(  "25" );
__(  "26" );
__(  "29" );
__(  "30" );
__(  "31" );
__(  "32" );
__(  "33" );
__(  "34" );
__(  "35" );
__(  "36" );
__(  "37" );
__(  "38" );
__(  "39" );
__(  "40" );
__(  "41" );
__(  "42" );
__(  "43" );
__(  "44" );
__(  "Monday" );
__(  "Tuesday" );
__(  "Wednesday" );
__(  "Thursday" );
__(  "Friday" );
__(  "Saturday" );
__(  "Sunday" );
__(  "N" );
__(  "E" );
__(  "W" );
__(  "S" );
__(  "30% Chance Drizzle" );
__(  "30% Chance Freezing Drizzle" );
__(  "30% Chance Freezing Rain" );
__(  "30% Chance Frozen Drizzle" );
__(  "30% Chance Frozen Mix" );
__(  "30% Chance Rain Shower" );
__(  "30% Chance Snow Shower" );
__(  "30% Chance of Drizzle" );
__(  "30% Chance of Flurry" );
__(  "30% Chance of Flurry" );
__(  "30% Chance of Frozen Mix" );
__(  "30% Chance of Light Snow" );
__(  "30% Chance of Rain" );
__(  "30% Chance of Sleet" );
__(  "30% Chance of Snow" );
__(  "30% Chance of Storms" );
__(  "40% Chance Drizzle" );
__(  "40% Chance Fozen Drizzle" );
__(  "40% Chance Freezing Drizzle" );
__(  "40% Chance Freezing Rain" );
__(  "40% Chance Frozen Drizzle" );
__(  "40% Chance Frozen Mix" );
__(  "40% Chance Rain Shower" );
__(  "40% Chance Snow Shower" );
__(  "40% Chance of Drizzle" );
__(  "40% Chance of Flurry" );
__(  "40% Chance of Frozen Mix" );
__(  "40% Chance of Light Snow" );
__(  "40% Chance of Rain" );
__(  "40% Chance of Sleet" );
__(  "40% Chance of Snow" );
__(  "40% Chance of Storms" );
__(  "50% Chance Freezing Drizzle" );
__(  "50% Chance Freezing Rain" );
__(  "50% Chance Rain Shower" );
__(  "50% Chance Snow Shower" );
__(  "50% Chance of Drizzle" );
__(  "50% Chance of Flurry" );
__(  "50% Chance of Frozen Mix" );
__(  "50% Chance of Light Snow" );
__(  "50% Chance of Rain" );
__(  "50% Chance of Sleet" );
__(  "50% Chance of Snow" );
__(  "50% Chance of Storms" );
__(  "Chance Freezing Drizzle" );
__(  "Chance Freezing Rain" );
__(  "Chance Rain Shower" );
__(  "Chance Snow Shower" );
__(  "Chance of Drizzle" );
__(  "Chance of Flurry" );
__(  "Chance of Freezing Drizzle" );
__(  "Chance of Frozen Drizzle" );
__(  "Chance of Frozen Mix" );
__(  "Chance of Light Snow" );
__(  "Chance of Rain" );
__(  "Chance of Rain Showers" );
__(  "Chance of Sleet " );
__(  "Chance of Snow" );
__(  "Chance of Snow Showers" );
__(  "Chance of Storms" );
__(  "Clear" );
__(  "Clearing" );
__(  "Cloudy" );
__(  "Drizzle" );
__(  "Fair" );
__(  "Flurries" );
__(  "Fog" );
__(  "Foggy" );
__(  "Freezing Drizzle" );
__(  "Freezing Rain" );
__(  "Frozen Mix" );
__(  "Hazy" );
__(  "Headline" );
__(  "Heavy Rain" );
__(  "Heavy Snow" );
__(  "Hot and Humid" );
__(  "Increasing Clouds" );
__(  "Light Snow" );
__(  "Mostly Clear" );
__(  "Mostly Cloudy" );
__(  "Mostly Sunny" );
__(  "Nowcast" );
__(  "Partly Cloudy" );
__(  "Partly Sunny" );
__(  "Rain" );
__(  "Rain Showers" );
__(  "Scattered Showers" );
__(  "Scattered Thunderstorms" );
__(  "Sleet" );
__(  "Snow" );
__(  "Snow Showers" );
__(  "Sunny" );
__(  "Thunderstorms" );
__(  "Unknown" );
__(  "Very Cold" );
__(  "Very Hot" );
__(  "Warm and Humid" );
__(  "Windy" );

// DarkSky translations
__(  "Clear" );
__(  "Possible Light Precipitation" );
__(  "Light Precipitation" );
__(  "Possible Light Precipitation" );
__(  "Light Precipitation" );
__(  "Precipitation" );
__(  "Heavy Precipitation" );
__(  "Possible Drizzle" );
__(  "Drizzle" );
__(  "Possible Light Rain" );
__(  "Light Rain" );
__(  "Rain" );
__(  "Heavy Rain" );
__(  "Possible Light Sleet" );
__(  "Light Sleet" );
__(  "Possible Light Sleet" );
__(  "Light Sleet" );
__(  "Sleet" );
__(  "Heavy Sleet" );
__(  "Possible Flurries" );
__(  "Flurries" );
__(  "Possible Light Snow" );
__(  "Light Snow" );
__(  "Snow" );
__(  "Heavy Snow" );
__(  "Windy" );
__(  "Dangerously Windy" );
__(  "Foggy" );
__(  "Mostly Cloudy" );
__(  "Overcast" );
__(  "Dry and Breezy" );
__(  "Drizzle and Dangerously Windy" );
__(  "Humid and Partly Cloudy" );
__(  "Clear for the hour." );
__(  "Flurries starting in 35 min." );
__(  "Light rain stopping in 15 min." );
__(  "Heavy sleet starting in 20 min., stopping 30 min. later." );
__(  "Rain stopping in 25 min., starting again 8 min. later." );
__(  "Mostly cloudy throughout the day." );
__(  "Light sleet starting in the morning." );
__(  "Windy until tonight." );
__(  "Heavy precipitation until afternoon." );
__(  "Breezy in the afternoon." );
__(  "Snow later this evening and tomorrow morning." );
__(  "Heavy rain until later this morning, starting again this evening." );
__(  "Overcast starting in the evening, continuing until night." );
__(  "Light sleet later this afternoon and foggy tomorrow morning." );
__(  "Dangerously windy starting this morning, continuing until this afternoon, and sleet tomorrow morning." );
__(  "Overcast starting later tonight and heavy snow tomorrow afternoon." );
__(  "Dry tonight and light precipitation starting tomorrow evening, continuing until tomorrow night." );
__(  "Snow (5 in.) overnight." );
__(  "Light snow (2 cm.) later this morning." );
__(  "Heavy snow (8\u201312 in.) throughout the day." );
__(  "Snow (< 1 cm.) in the afternoon." );
__(  "No precipitation throughout the week, with high temperatures peaking at 85\u00B0F tomorrow." );
__(  "Mixed precipitation over the weekend, with high temperatures rising to 32\u00B0C on Thursday." );
__(  "Drizzle on Monday, with high temperatures bottoming out at 15\u00B0F on Friday." );
__(  "Light snow on Tuesday and next Wednesday, with high temperatures falling to 0\u00B0C on Sunday." );
__(  "Precipitation today through Saturday, with high temperatures peaking at 100\u00B0F on Monday." );
__(  "Mixed precipitation (1\u20133 in. of snow) throughout the day." );
__(  "Heavy Snow (1\u20133 in.)" );
__(  "Heavy Snow (3\u20135 cm.)" );
__(  "Possible Thunderstorms" );
__(  "Heavy Rain and Thunderstorms" );
__(  "Drizzle starting in < 1 min." );
__(  "rain" );
__(  "snow" );
__(  "sleet" );
  }
?>
